### PR TITLE
Calculate TotalCreditPoints

### PR DESCRIPTION
**Pull request by ghost**
Please review @lauralindal !

### CODE REVIEW

**Comment by ghost** [comment]
@schultyy  we are making 
```
var userModules = users.students[0].tracked_modules;
var modules = moduleplan.degree_course.modules;
```
twice, because it somehow won't work as a global variable (above render())... any idea why?

**Comment by schultyy** [comment]
@lenakoester Does ist produce an error? If yes, which error? And what is the behavior here?

**Comment by lauralindal** [comment]
@schultyy 
currently we do
```
var userModules = users.students[0].tracked_modules;
var modules = moduleplan.degree_course.modules;
```
in `getSemestersForUser` as well as in `calculateTotalCredits`.
I would think that we should be able to take these variables out of there an instead only use them once, like so:
```
class Home extends React.Component {
  
  var userModules = users.students[0].tracked_modules;
  var modules = moduleplan.degree_course.modules;

  render() {
    var totalCreditPoints = this.calculateTotalCredits();
    var semesters = this.getSemestersForUser();
    return (
      <div>
      <ModulePlan semesters={semesters}/>
      <PlanningSection totalCreditPoints= {totalCreditPoints} />
      </div>
    );
  }

  getSemestersForUser() {
    var semesters = [1,2,3,4,5,6].map(function(semester) {
      var filteredModules = modules.filter(function(module) {
        return module.recommended_semester === semester;
      });
      return filteredModules.map(function(module) {
        var userModule = userModules.find(function(userModule) {
          return userModule.module_id === module.id;
        });
        return {
         module: module,
         userModule: userModule
        }
      });
    });
    return semesters;
  }

 calculateTotalCredits() {
  var totalCredits= 0;
  for (var i = 0; i < userModules.length; i++) {
    if (userModules[i].status === "completed"){
      totalCredits= totalCredits + modules[i].cp;
    }
  }
  return totalCredits;
  };
}

export default Home
```
But that lead to the following error:
```
ERROR in ./src/Home.js
Module build failed: SyntaxError: Unexpected token, expected ( (9:6)

   7 | class Home extends React.Component {
   8 | 
>  9 |   var userModules = users.students[0].tracked_modules;
     |       ^
  10 |   var modules = moduleplan.degree_course.modules;
  11 | 
  12 |   render() {

 @ ./src/application.js 11:12-29
```

**Comment by schultyy** [comment]
I see. Then it makes sense to convert these to instance variables:

```javascript
class Home extends React.Component {
  constructor() {
    super(); 
    this.userModules = users.students[0].tracked_modules;
    this.modules = moduleplan.degree_course.modules;
  }
}
```

Then these are available in the whole class via `this.userModules` and `this.modules`.

**Comment by ghost** [comment]
@schultyy We tried your suggestions, but since it still gives us an error, we left it as it was. The data will eventually come from the database and we will improve it later. Is that okay?

**Review by schultyy — APPROVED** [review]

**Pull request merged**
