### PR TITLE
17 structure rso

### PR DESCRIPTION
**Pull request by noobiba**
This pull request risolves "5.1 Create HTML structure for Regelstudienordnung".

### CODE REVIEW

**Comment by lauralindal** [comment]
So if I look at this from my machine, we (still) have two index.html - the one that's not in our public folder looks like this, if I open the file in my browser:
screenshot from 2016-11-06 16 56 37
Quite well done! <3

The other file, `public/index.html` looks the same when I just open the file, but when I navigate to it via `localhost:8080`, it looks like this:
screenshot from 2016-11-06 16 58 04

I'd guess that we're not loading the .js files in correct order or place, maybe @schultyy can help us here? As for the HTML, I have no idea if that's best practice HTML (because I have no idea about best practice HTML), but I'm hoping @sarahkami or @lewiscowper can have a look :)

**Comment by schultyy** [comment]
From what I can see right now is that there's one `index.html` too much. I had a look at the webpack config and saw you're serving files from `public`. This allows you to get rid of the `index.html` in the root directory.

**Comment by schultyy** [comment]
Concerning the styles: For now it should be sufficient to move `css/` to `public/css`. Since hoodie serves all requests right now, all files you reference in `index.html` must be available in `public/`.

**Comment by lauralindal** [comment]
Looks good now :+1:

**Review by lauralindal — APPROVED** [review]

**Pull request merged**
